import type { CSSProperties } from 'react'
import {
  Archive,
  Battery,
  Bell,
  Book,
  Bookmark,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  ClipboardList,
  Clock,
  Code,
  Coffee,
  Cpu,
  CreditCard,
  DollarSign,
  FileText,
  Flag,
  Folder,
  Gift,
  GraduationCap,
  HardDrive,
  Headphones,
  Heart,
  Home,
  Key,
  Keyboard,
  Laptop,
  Lightbulb,
  ListChecks,
  Lock,
  Mail,
  MapPin,
  Monitor,
  Mouse,
  Package,
  Phone,
  Plug,
  Printer,
  Receipt,
  Shield,
  ShoppingCart,
  Smartphone,
  Star,
  Tag,
  Truck,
  User,
  Users,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon
} from 'lucide-react'

/** Icons offered in the icon picker, stored by name (notes.icon / folders.icon). Anything else stored is an emoji. */
export const ICONS: Record<string, LucideIcon> = {
  FileText,
  Folder,
  Star,
  Heart,
  Bookmark,
  Flag,
  Lightbulb,
  Zap,
  Briefcase,
  Wrench,
  Cpu,
  Smartphone,
  Laptop,
  Monitor,
  HardDrive,
  Battery,
  Plug,
  Wifi,
  Printer,
  Camera,
  Headphones,
  Keyboard,
  Mouse,
  Package,
  Truck,
  ShoppingCart,
  Receipt,
  DollarSign,
  CreditCard,
  Calendar,
  Clock,
  Bell,
  Mail,
  Phone,
  User,
  Users,
  Building2,
  Home,
  MapPin,
  Key,
  Lock,
  Shield,
  Code,
  Book,
  GraduationCap,
  ClipboardList,
  ListChecks,
  Archive,
  Tag,
  Coffee,
  Gift
}

/** Colour palette ids; the actual colours are CSS variables (--c-<id>) with light and dark variants. */
export const COLORS = ['gray', 'red', 'orange', 'yellow', 'green', 'teal', 'blue', 'purple', 'pink'] as const

export const colorStyle = (color: string): CSSProperties | undefined => (color ? { color: `var(--c-${color})` } : undefined)

/** A note's or folder's icon: a picker icon (tinted with its colour), an emoji, or the fallback icon. */
export function ItemIcon({ icon, color, fallback: Fallback, className }: { icon: string; color: string; fallback: LucideIcon; className?: string }) {
  const Picked = icon ? ICONS[icon] : undefined
  if (Picked) return <Picked className={className} style={colorStyle(color)} />
  if (icon) return <span className={`emoji-icon ${className ?? ''}`}>{icon}</span>
  return <Fallback className={className} style={colorStyle(color)} />
}
